### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by yurovant**
Fix typo: `depulicated` => `duplicated`

### CODE REVIEW

**Comment by yama-t** [comment]
すみません、duplicated（重複）のtypoではなく、deprecated（非推奨）のtypoではないでしょうか？

**Comment by yurovant** [comment]
Hi @yama-t, could you please translate your comment to English? Thanks.

**Comment by yama-t** [comment]
I think this line should be modified as follows,
I guess "depulicated" is typo of  "deprecated".
```
@depulicated → @deprecated
```

**Comment by yurovant** [comment]
Ah, now I see your point. Thanks for clarification. :)

**Comment by yama-t** [comment]
I'm glad to be able to communicate.😃

**Comment by frontainer** [comment]
Thanks all😃  Merged your PR https://github.com/frontainer/frontnote/pull/10

**Pull request closed without merging**
